apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: microservice-local
data:
  LOG_LEVEL: "debug"
  ENVIRONMENT: "local"
  PORT: "8080"
  CACHE_TTL: "60"
  DB_MAX_CONNECTIONS: "10"
  ENABLE_PROFILING: "true"