apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: microservice-local
spec:
  type: NodePort  # Direct access for local development
  selector:
    app: api-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080  # Fixed port for local access
  - name: metrics
    port: 9090
    targetPort: 9090
    nodePort: 30090